name: Deploy buy runner

on:
  push:
    branches: [ "master", "main" ]
jobs:
  test:
    runs-on: macos-latest
    steps: # Перечень шагов, которые необходимо выполнить в рамках джобы.
      - name: cd into repo # Название шага
        uses: actions/checkout@v3 # Ключевое слово uses используется для запуска заранее
      # созданного набора команд. В данном случае используем дефолтную команду
      # для обновления проекта до последнего коммита.
      - name: set up Java and Maven # Настраиваем Java и Maven.
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: run tests
        run: mvn test # Запускаем тесты.
  deploy:
    runs-on: self-hosted
    needs: test
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: prepare environment
        run: |
          docker-compose down
          docker system prune -a -f
      - name: docker-compose deploy
        run: docker-compose up -d

